In [2]:
#sort , serach, counting fun

In [3]:
import numpy as np

In [9]:
arr = np.array([4,3,4,5,6,72,3,3,544,5,6,6])
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [10]:
np.sort(arr) # acsending ordder

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 544])

In [11]:
np.searchsorted(arr,34)

12

In [13]:
arr1 = np.array([0,2,34,454,0,0,0,0,0])

In [14]:
np.count_nonzero(arr1)

3

In [15]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [16]:
np.where(arr>6)

(array([5, 8]),)

In [18]:
np.extract(arr>6 , arr)

array([ 72, 544])

In [19]:
#-------------BYTE SWAPPING

arr.byteswap()

array([ 288230376151711744,  216172782113783808,  288230376151711744,
        360287970189639680,  432345564227567616, 5188146770730811392,
        216172782113783808,  216172782113783808, 2306405959167115264,
        360287970189639680,  432345564227567616,  432345564227567616])

In [20]:
#----------copies & views

arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [23]:
#---copy, deep copy, loc are diff

a= np.copy(arr)
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [25]:
arr[0]=2
arr

array([  2,   3,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [26]:
a 

array([  4,   3,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [28]:
# -----view copy , swalo copy loc are same

b=arr
b

array([  2,   3,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [30]:
b[1]=7
b

array([  2,   7,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [31]:
arr

array([  2,   7,   4,   5,   6,  72,   3,   3, 544,   5,   6,   6])

In [37]:
#----------MATRIX LIBRARY

import numpy.matlib as nm

In [38]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [39]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [42]:
#---- LINEAR ALGEBRA   - 

ar1 = np.random.randint([[2,3] , [4,5]])
ar1

array([[0, 1],
       [3, 1]])

In [43]:
ar2 = np.random.randint([[5,3] , [2,5]])
ar2

array([[3, 0],
       [0, 4]])

In [44]:
np.dot(ar1, ar2)

array([[0, 4],
       [9, 4]])

In [45]:
ar1@ar2  # matrix multiplication

array([[0, 4],
       [9, 4]])