In [1]:
# -----------array manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10, (3,4))

In [7]:
arr

array([[5, 7, 3, 5],
       [2, 8, 5, 5],
       [8, 3, 3, 3]])

In [5]:
arr.reshape(6,2)

array([[5, 7],
       [3, 5],
       [2, 8],
       [5, 5],
       [8, 3],
       [3, 3]])

In [8]:
arr

array([[5, 7, 3, 5],
       [2, 8, 5, 5],
       [8, 3, 3, 3]])

In [9]:
arr.T

array([[5, 2, 8],
       [7, 8, 3],
       [3, 5, 3],
       [5, 5, 3]])

In [10]:
# -------------convert  2d into 1d
arr.flatten()

array([5, 7, 3, 5, 2, 8, 5, 5, 8, 3, 3, 3])

In [13]:
#----------expend is - 1d to 2d

arr1 = np.array([1,2,3,3,4])
arr1.ndim

1

In [14]:
np.expand_dims(arr1, axis = 1)  # axis = 1 col

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [17]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 3, 4]])

In [21]:
data = np.array([[1] ,[2], [3]])
data

array([[1],
       [2],
       [3]])

In [22]:
np.squeeze(data)

array([1, 2, 3])

In [23]:
#----repeate()
arr1

array([1, 2, 3, 3, 4])

In [24]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [27]:
np.roll(arr1 , 2)

array([3, 4, 1, 2, 3])

In [28]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [30]:
#----------------BINARY OPERATION + - / *

arr2 = np.random.randint(1,10 ,(3,4))
arr2

array([[8, 9, 1, 6],
       [6, 1, 8, 3],
       [5, 4, 6, 8]])

In [31]:
arr3 = np.random.randint(1,10 ,(3,4))
arr3

array([[7, 4, 2, 6],
       [3, 7, 1, 2],
       [7, 2, 3, 1]])

In [32]:
arr2+arr3

array([[15, 13,  3, 12],
       [ 9,  8,  9,  5],
       [12,  6,  9,  9]])

In [33]:
arr2*arr3

array([[56, 36,  2, 36],
       [18,  7,  8,  6],
       [35,  8, 18,  8]])

In [34]:
arr2%arr3  # remainder

array([[1, 1, 1, 0],
       [0, 1, 0, 1],
       [5, 0, 0, 0]])

In [35]:
arr2 & arr3

array([[0, 0, 0, 6],
       [2, 1, 0, 2],
       [5, 0, 2, 0]])

In [39]:
#---------STRING FUN

ast = np.array(['sufeeya', 'khan'])
ast

array(['sufeeya', 'khan'], dtype='<U7')

In [40]:
np.char.upper(ast)

array(['SUFEEYA', 'KHAN'], dtype='<U7')

In [41]:
np.char.title(ast)

array(['Sufeeya', 'Khan'], dtype='<U7')

In [42]:
# -------------MATHEMATICAL FUN

arr2

array([[8, 9, 1, 6],
       [6, 1, 8, 3],
       [5, 4, 6, 8]])

In [43]:
np.sin(arr2)

array([[ 0.98935825,  0.41211849,  0.84147098, -0.2794155 ],
       [-0.2794155 ,  0.84147098,  0.98935825,  0.14112001],
       [-0.95892427, -0.7568025 , -0.2794155 ,  0.98935825]])

In [44]:
np.cos(arr2)

array([[-0.14550003, -0.91113026,  0.54030231,  0.96017029],
       [ 0.96017029,  0.54030231, -0.14550003, -0.9899925 ],
       [ 0.28366219, -0.65364362,  0.96017029, -0.14550003]])

In [45]:
np.log10(arr2)

array([[0.90308999, 0.95424251, 0.        , 0.77815125],
       [0.77815125, 0.        , 0.90308999, 0.47712125],
       [0.69897   , 0.60205999, 0.77815125, 0.90308999]])

In [46]:
np.exp(arr2)

array([[2.98095799e+03, 8.10308393e+03, 2.71828183e+00, 4.03428793e+02],
       [4.03428793e+02, 2.71828183e+00, 2.98095799e+03, 2.00855369e+01],
       [1.48413159e+02, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03]])