In [ ]:
NumPy is a Python library.
NumPy is used for working with arrays and matrices.
numpy is for mathematical opreation
NumPy is short for "Numerical Python".
created in 2005 by Travis Oliphant.

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
#-----in numpy array is super class  , and matrix subclass / subset of arr

ar = np.array(l) 
ar#convert list into arr , array pack

array([1, 2, 3, 4])

In [4]:
type(ar) 

numpy.ndarray

In [5]:
np.array([[1,2] , [3,4]]) #2d arr , coprdinate 0,1,2 and values 3.4,2,5,6

array([[1, 2],
       [3, 4]])

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
#-------------matrix bydefault 2d , subset of array

b= np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [8]:
np.asanyarray(b) #cant convert into arr

matrix([[1, 2, 3, 4]])

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
print(ar[2] + ar[3])

7


In [6]:
c=ar
c # c point ar var , c is swalo   location are same , view

array([1, 2, 3, 4])

In [7]:
c[0]=100
c

array([100,   2,   3,   4])

In [8]:
ar

array([100,   2,   3,   4])

In [9]:
d= np.copy(ar)  #d -copy ar var value in location  , deep copy  location are diff
d

array([100,   2,   3,   4])

In [10]:
ar[1]=300
ar  #d cant not change

array([100, 300,   3,   4])

In [11]:
d

array([100,   2,   3,   4])

In [19]:
#-----------ff() iske andr jo fun  likhenge uske according data generate krega
# its help to interms of genertate array at any point
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [21]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [22]:
it = (i*i for i in range (5))

In [23]:
np.fromiter(it, float)

array([ 0.,  1.,  4.,  9., 16.])

In [24]:
np.fromstring('234 345', sep= ' ')

array([234., 345.])

In [33]:
#-------------numpy data type

In [25]:
l= [2,3,4,5,6]

In [26]:
arr = np.array(l)
arr

array([2, 3, 4, 5, 6])

In [35]:
#------many dimensions the arrays have:

arr.ndim

1

In [27]:
ar2= np.array([[1, 2, 3], [4, 5, 6]])
ar2.ndim

2

In [32]:
ar2.shape # 2, 3 --2r and 3col

(2, 3)

In [2]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d.ndim

3

In [4]:
d.size

12

In [5]:
d.shape

(2, 2, 3)

In [30]:
ar3 = np.array([1, 2, 3, 4], ndmin=6)

print(ar3)
print('number of dimensions :', ar3.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


In [36]:
ar4 = np.array([(1.4, 45,45) , (23,45,66)]) # all float dtype , float take more space than int
ar4 

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [37]:
list(range(5))    # range always take int, not float 

[0, 1, 2, 3, 4]

In [39]:
#-----produce floating number with the help of numpy

np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [40]:
np.arange(2.5,5.6,.3) #jumpe with .3

array([2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6, 4.9, 5.2, 5.5])

In [41]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
on = np.ones((2,2,3))
on

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
on+5*4

array([[[21., 21., 21.],
        [21., 21., 21.]],

       [[21., 21., 21.],
        [21., 21., 21.]]])

In [13]:
np.empty((3,6))

array([[4.64428032e-310, 0.00000000e+000, 0.00000000e+000,
        6.54142915e-321, 6.36598742e-314, 0.00000000e+000],
       [6.54142915e-321, 2.96439388e-322, 0.00000000e+000,
        6.54142915e-321, 6.12641401e-322, 0.00000000e+000],
       [6.56119178e-321, 5.23709585e-322, 0.00000000e+000,
        6.56119178e-321, 2.12199584e-314, 0.00000000e+000]])

In [14]:
#-identity matrix - square matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.logspace(2,5 , 10 , base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [18]:
# -------in numpy there is a random (), ussme randomly jis shape ya size ka data generate kr skte h

ar5 = np.random.randn(3,4)   # randn me mean avg=0 , std =1 data produce krega
ar5

array([[-2.3021792 , -1.38274662, -0.58275382, -0.47815288],
       [ 1.13434554,  1.39465514,  1.17288041, -1.02436127],
       [-1.24263789, -1.68759586,  0.55126384, -0.1836619 ]])

In [19]:
import pandas as pd

pd.DataFrame(ar5)

0         1         2         3
0 -2.302179 -1.382747 -0.582754 -0.478153
1  1.134346  1.394655  1.172880 -1.024361
2 -1.242638 -1.687596  0.551264 -0.183662

In [20]:
np.random.rand(3,4)

array([[0.77418894, 0.45801848, 0.49166774, 0.22758498],
       [0.18104753, 0.71187044, 0.91101057, 0.26393219],
       [0.46532   , 0.68244877, 0.56999202, 0.66280986]])

In [25]:
pd.DataFrame(np.random.randint(1,110, (300,400)) ).to_csv('array_data.csv')  # 1,110 se random data lega

In [27]:
#------------reshape 

ar6 = np.random.rand(3,4)
ar6

array([[0.69836891, 0.30566956, 0.62735794, 0.37988818],
       [0.48859594, 0.36829495, 0.50411307, 0.31680888],
       [0.61358671, 0.79847532, 0.14456176, 0.47119689]])

In [44]:
a= ar6.reshape(6,2) # reshape 3,4 to 6X2
a

array([[0.69836891, 0.30566956],
       [0.62735794, 0.37988818],
       [0.48859594, 0.36829495],
       [0.50411307, 0.31680888],
       [0.61358671, 0.79847532],
       [0.14456176, 0.47119689]])

In [45]:
a[1][1]

0.3798881777762513

In [49]:
a[2:5, 1]

array([0.36829495, 0.31680888, 0.79847532])

In [46]:
a1 = np.array([1, 2, 3, 4, 5, 6])

index = np.where(a1==3)
index

(array([2]),)

In [50]:
ar7 = np.random.randint(1,110, (5,5))
ar7

array([[ 27,  47,   2,  16,  19],
       [ 52, 104,  73,  74,  85],
       [  9,  57,  52,  26,   6],
       [ 99,  64,   7,  21,   6],
       [103, 109,  87, 101,  26]])

In [51]:
ar7 >50

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [False,  True,  True, False, False],
       [ True,  True, False, False, False],
       [ True,  True,  True,  True, False]])

In [53]:
ar7[ar7 >50]

array([ 52, 104,  73,  74,  85,  57,  52,  99,  64, 103, 109,  87, 101])

In [54]:
ar7

array([[ 27,  47,   2,  16,  19],
       [ 52, 104,  73,  74,  85],
       [  9,  57,  52,  26,   6],
       [ 99,  64,   7,  21,   6],
       [103, 109,  87, 101,  26]])

In [56]:
ar7[2:4 , [1,2]]  #2:4 rows , 1,2 col

array([[57, 52],
       [64,  7]])

In [59]:
ar7[0,0]  #[0][0]

27

In [61]:
ar7[0,0]=500
ar7

array([[500,  47,   2,  16,  19],
       [ 52, 104,  73,  74,  85],
       [  9,  57,  52,  26,   6],
       [ 99,  64,   7,  21,   6],
       [103, 109,  87, 101,  26]])

In [5]:
arr1= np.random.randint(1,3 , (3,3))
arr2= np.random.randint(1,3 , (3,3))

In [6]:
arr1

array([[1, 2, 1],
       [2, 2, 2],
       [2, 2, 1]])

In [7]:
arr2

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [8]:
arr1+arr2 #this not matrix sum , this is index sum

array([[3, 4, 2],
       [4, 4, 4],
       [4, 3, 3]])

In [ ]:
#-martix multiplication , 1 rule 1m rxC , 2m Rxc  C of 1m and R of 2m should be qual

2,2,1   1,2,2      2x1+2x2+1x1  2x2+2x1+1x1  2x2+2x1+1x1
2,1,2   2,1,1      2x1+1x2+2x1  2x2+1x1+2x1  
1,2,1   1,1,1

In [9]:
arr1@arr2   #----@ help to multiply matrix

array([[ 8,  7,  7],
       [12, 10, 10],
       [10,  9,  8]])

In [38]:
arr1/0

/tmp/ipykernel_70/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [11]:
arr1+100

array([[101, 102, 101],
       [102, 102, 102],
       [102, 102, 101]])

In [12]:
#---------broadcasting  , row by row broadcasting kr ra h , means  change entier row
 
arr3 = np.zeros((4,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [24]:
arr3*row

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
#----------col wise broadcasting , firslty rotate row , but rotation only 2d

row2 = np.array([[1,2,3,4]])
row2

array([[1, 2, 3, 4]])

In [27]:
row2.T # transpose rotate into row to col

array([[1],
       [2],
       [3],
       [4]])

In [23]:
row2.T+arr3    # then broadcasting

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [35]:
arr4 = np.random.randint(5,7 ,(3,4))
arr4

array([[5, 5, 6, 6],
       [6, 6, 5, 6],
       [6, 5, 5, 5]])

In [36]:
np.sqrt(arr4)

array([[2.23606798, 2.23606798, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.23606798, 2.44948974],
       [2.44948974, 2.23606798, 2.23606798, 2.23606798]])

In [37]:
np.log10(arr4)

array([[0.69897   , 0.69897   , 0.77815125, 0.77815125],
       [0.77815125, 0.77815125, 0.69897   , 0.77815125],
       [0.77815125, 0.69897   , 0.69897   , 0.69897   ]])