In [1]:
# -----------array manipulation

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, (3,4))

In [3]:
arr

array([[7, 5, 2, 1],
       [8, 6, 1, 3],
       [6, 9, 6, 5]], dtype=int32)

In [5]:
arr.reshape(6,2)

array([[7, 5],
       [2, 1],
       [8, 6],
       [1, 3],
       [6, 9],
       [6, 5]], dtype=int32)

In [6]:
arr

array([[7, 5, 2, 1],
       [8, 6, 1, 3],
       [6, 9, 6, 5]], dtype=int32)

In [7]:
arr.T

array([[7, 8, 6],
       [5, 6, 9],
       [2, 1, 6],
       [1, 3, 5]], dtype=int32)

In [8]:
# -------------convert  2d , 3d into 1d
arr.flatten()

array([7, 5, 2, 1, 8, 6, 1, 3, 6, 9, 6, 5], dtype=int32)

In [40]:
#----------expend is - 1d to 2d

arr1 = np.array([1,2,3,3,4])
arr1.ndim

1

In [41]:
np.expand_dims(arr1, axis = 1)  # axis = 1 col ke across expand krdiya 1d to 2d

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [42]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 3, 4]])

In [49]:
arr

array([[7, 5, 2, 1],
       [8, 6, 1, 3],
       [6, 9, 6, 5]], dtype=int32)

In [50]:
arr.squeeze() # with multiple elements squeeze doesnt work

array([[7, 5, 2, 1],
       [8, 6, 1, 3],
       [6, 9, 6, 5]], dtype=int32)

In [47]:
data = np.array([[1] ,[2], [3]]) # works with single element
data

array([[1],
       [2],
       [3]])

In [48]:
np.squeeze(data) 

array([1, 2, 3])

In [23]:
#----repeate()
arr1

array([1, 2, 3, 3, 4])

In [51]:
np.repeat(arr1,5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [52]:
np.roll(arr1 , 2)

array([3, 4, 1, 2, 3])

In [53]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [54]:
#----------------BINARY OPERATION + - / *

arr2 = np.random.randint(1,10 ,(3,4))
arr2

array([[1, 1, 2, 9],
       [8, 4, 3, 8],
       [2, 2, 6, 1]], dtype=int32)

In [55]:
arr3 = np.random.randint(1,10 ,(3,4))
arr3

array([[4, 8, 4, 2],
       [8, 1, 6, 2],
       [3, 4, 9, 5]], dtype=int32)

In [56]:
arr2+arr3

array([[ 5,  9,  6, 11],
       [16,  5,  9, 10],
       [ 5,  6, 15,  6]], dtype=int32)

In [57]:
arr2*arr3

array([[ 4,  8,  8, 18],
       [64,  4, 18, 16],
       [ 6,  8, 54,  5]], dtype=int32)

In [58]:
arr2%arr3  # remainder

array([[1, 1, 2, 1],
       [0, 0, 3, 0],
       [2, 2, 6, 1]], dtype=int32)

In [59]:
arr2 & arr3

array([[0, 0, 0, 0],
       [8, 0, 2, 0],
       [2, 0, 0, 1]], dtype=int32)

In [61]:
~arr2

array([[ -2,  -2,  -3, -10],
       [ -9,  -5,  -4,  -9],
       [ -3,  -3,  -7,  -2]], dtype=int32)

In [62]:
#---------STRING FUN

ast = np.array(['sufeeya', 'khan'])
ast

array(['sufeeya', 'khan'], dtype='<U7')

In [67]:
np.char.upper(ast)

array(['SUFEEYA', 'KHAN'], dtype='<U7')

In [68]:
np.char.title(ast)

array(['Sufeeya', 'Khan'], dtype='<U7')

In [69]:
# -------------MATHEMATICAL FUN

arr2

array([[1, 1, 2, 9],
       [8, 4, 3, 8],
       [2, 2, 6, 1]], dtype=int32)

In [70]:
np.sin(arr2)

array([[ 0.84147098,  0.84147098,  0.90929743,  0.41211849],
       [ 0.98935825, -0.7568025 ,  0.14112001,  0.98935825],
       [ 0.90929743,  0.90929743, -0.2794155 ,  0.84147098]])

In [71]:
np.cos(arr2)

array([[ 0.54030231,  0.54030231, -0.41614684, -0.91113026],
       [-0.14550003, -0.65364362, -0.9899925 , -0.14550003],
       [-0.41614684, -0.41614684,  0.96017029,  0.54030231]])

In [74]:
np.tan(arr2)

array([[ 1.55740772,  1.55740772, -2.18503986, -0.45231566],
       [-6.79971146,  1.15782128, -0.14254654, -6.79971146],
       [-2.18503986, -2.18503986, -0.29100619,  1.55740772]])

In [72]:
np.log10(arr2)

array([[0.        , 0.        , 0.30103   , 0.95424251],
       [0.90308999, 0.60205999, 0.47712125, 0.90308999],
       [0.30103   , 0.30103   , 0.77815125, 0.        ]])

In [73]:
np.exp(arr2)

array([[2.71828183e+00, 2.71828183e+00, 7.38905610e+00, 8.10308393e+03],
       [2.98095799e+03, 5.45981500e+01, 2.00855369e+01, 2.98095799e+03],
       [7.38905610e+00, 7.38905610e+00, 4.03428793e+02, 2.71828183e+00]])

In [76]:
np.power(arr2,2)

array([[ 1,  1,  4, 81],
       [64, 16,  9, 64],
       [ 4,  4, 36,  1]], dtype=int32)