In [ ]:
NumPy is a Python library.
NumPy is used for working with arrays and matrices.
numpy is for mathematical opreation
NumPy is short for "Numerical Python".
created in 2005 by Travis Oliphant.

In [ ]:
in numpy array is super class  , and matrix subclass / subset of arr

In [5]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [38]:
ar = np.array(l) 
ar #convert list into arr , array pack

array([1, 2, 3, 4])

In [11]:
type(ar)  # ndarray n dimensional array

numpy.ndarray

In [13]:
a2=np.array([[1,2] , [3,4]]) #2d arr , coordinate 0,1,2 and values 3.4,2,5,6
a2

array([[1, 2],
       [3, 4]])

In [14]:
np.asarray(a2) 

array([[1, 2],
       [3, 4]])

In [22]:
#-------------matrix bydefault 2d , subset of array

b= np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [23]:
np.asanyarray(b) #cant convert into arr , because matrix is subset or form of array

matrix([[1, 2, 3, 4]])

In [39]:
ar

array([1, 2, 3, 4])

In [40]:
print(ar[2] + ar[3])

7


In [41]:
# ar share same property and location with c 

c=ar
c # c point ar var , c is shallow location are same , view

array([1, 2, 3, 4])

In [42]:
c[0]=100 # shallow copy
c

array([100,   2,   3,   4])

In [43]:
ar

array([100,   2,   3,   4])

In [44]:
d= np.copy(ar)  #d -copy ar var value in location  , deep copy location are diff
d

array([100,   2,   3,   4])

In [46]:
ar[1]=200
ar  

array([100, 200,   3,   4])

In [47]:
d #d cant not change , buz d copy a in diff location 

array([100,   2,   3,   4])

#  ff() fromfunction()

In [19]:
#-----------ff() iske andr jo fun likhenge uske according data generate krega
# its help to interms of genertate array at any point

np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [48]:
np.fromfunction(lambda i,j : i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [21]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

# fromiter() fromstring()

In [60]:
it = (i+i for i in range (5))

In [61]:
np.fromiter(it, float )

array([0., 2., 4., 6., 8.])

In [ ]:
✅ Use np.array(listt) for string data.
✅ Use np.fromstring() only if you have a single numeric string or data.
❌ np.fromstring() does not work with a list of strings.

In [75]:
list=['a','b','sufeeya Parween']

np.fromstring(list, sep= ',')

TypeError: a bytes-like object is required, not 'list'

In [ ]:
TypeError because np.fromstring() expects a single string,
but you're passing a list. Additionally, np.fromstring() is designed for numeric data, 
so it won't work with non-numeric strings like 'a' and 'sufeeya Parween'.

In [84]:
# 1---approach
np.array(listt)  # Convert list to NumPy array

array(['a', 'b', 'sufeeya Parween'], dtype='<U15')

In [77]:
type(np_array)

numpy.ndarray

In [78]:
# convert str into arr
afs =np.fromstring('234 345', sep= ' ')
afs

array([234., 345.])

In [79]:
type(afs)

numpy.ndarray

In [83]:
numeric_string = "1,2,3,4"
np.fromstring(numeric_string, sep=',')

array([1., 2., 3., 4.])

# numpy data type

In [85]:
l= [2,3,4,5,6]

In [86]:
arr = np.array(l)
arr

array([2, 3, 4, 5, 6])

In [35]:
#------many dimensions the arrays have:

arr.ndim

1

In [87]:
ar2= np.array([[1, 2, 3], [4, 5, 6]])
ar2.ndim

2

In [88]:
arr.size

5

In [32]:
ar2.shape # 2, 3 --2r and 3col

(2, 3)

In [2]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d.ndim

3

In [4]:
d.size

12

In [5]:
d.shape

(2, 2, 3)

In [97]:
ar3 = np.array([1, 2, 3, 4], ndmin=6)

print(ar3)
print('number of dimensions :', ar3.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


In [98]:
ar4 = np.array([(1.4, 45,45) , (23,45,66)]) # all float dtype , float take more space than int
ar4 

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [37]:
list(range(5))    # range always take int, not float 

[0, 1, 2, 3, 4]

In [99]:
#-----produce floating number with the help of numpy

np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [40]:
np.arange(2.5,5.6,.3) #jumpe with .3

array([2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6, 4.9, 5.2, 5.5])

In [41]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
on = np.ones((2,3,2))
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [110]:
on+5*4

array([[[21., 21.],
        [21., 21.],
        [21., 21.]],

       [[21., 21.],
        [21., 21.],
        [21., 21.]]])

In [118]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.96342369e+296]])

In [108]:
#-identity matrix - square matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [119]:
np.logspace(2,5 , 10 , base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

# random data generate.
* *diff randn and rand:-
* 1-randn me mean avg=0 , std =1 data produce krega.
* 2-rand it just generate data randomly.


In [8]:
# -------in numpy there is a random (), ussme randomly jis shape ya size ka data generate kr skte h

ar5 = np.random.randn(3,4)   # randn me mean avg=0 , std =1 data produce krega
ar5

array([[-1.65254774,  0.51132459, -0.62603704,  0.24636539],
       [ 0.92775926,  0.02695142, -0.48221   ,  0.15938931],
       [-0.87868363, -0.5948429 ,  0.23810937, -1.54889955]])

In [9]:
import pandas as pd

pd.DataFrame(ar5)

0         1         2         3
0 -1.652548  0.511325 -0.626037  0.246365
1  0.927759  0.026951 -0.482210  0.159389
2 -0.878684 -0.594843  0.238109 -1.548900

In [122]:
np.random.rand(3,4) # its just generate data randomly

array([[0.03116431, 0.17306191, 0.73429533, 0.40644832],
       [0.10538608, 0.99913422, 0.87858674, 0.81929505],
       [0.8356181 , 0.77927034, 0.55831006, 0.53820805]])

In [29]:
# only produce int 

np.random.randint(1,200, (5,4))

array([[ 89, 139,   8, 171],
       [ 36, 145, 114,  79],
       [ 40, 185, 143, 192],
       [ 21,  80,  98,  23],
       [ 39, 196,  66, 115]], dtype=int32)

In [30]:
pd.DataFrame(np.random.randint(1,110, (300,400)) ).to_csv('array_data.csv')  # 1,110 se random data lega

In [31]:
pd.read_csv('array_data.csv')

Unnamed: 0   0   1    2    3   4    5    6   7   8  ...  390  391  392  \
0             0  12  65    1   27  32   56   90  54  20  ...   28    5  102   
1             1  65  63   66   85  46   69   82  88  53  ...   25   81   45   
2             2  13  70   13  100  32   97  108  31  82  ...   81   49   77   
3             3   8  87   66   55  89   38    9  98  40  ...   46   80   16   
4             4  71  38   55   35  76   98   21  45  14  ...   18  100   11   
..          ...  ..  ..  ...  ...  ..  ...  ...  ..  ..  ...  ...  ...  ...   
295         295  89  20   64   19  14  104   33  14  38  ...   19  105   59   
296         296  66  98   51   45  63   22   30  42  25  ...   52   84    8   
297         297   8  98  106   32  60   47   60  57  85  ...   30   39   19   
298         298  63  32   95   58  21   56    8  42  34  ...   21   45  106   
299         299  84  88   23   31  75   61   80  82  91  ...   92   51   22   

     393  394  395  396  397  398  399  
0     26   67   91   78   89   74   34  
1     88   52   62   64    2    1    3  
2     34   21    3   48   41  107   77  
3     39   16   25  105   81  103   78  
4     22   20   23   46   19   17  105  
..   ...  ...  ...  ...  ...  ...  ...  
295  107    6   31   84   90   12   68  
296   53  105   38   74   89   32   72  
297   58   22   95   85    8   11   22  
298   79   33   67   83   12   10   17  
299   73   91   28   32   63    7   22  

[300 rows x 401 columns]

In [12]:
#------------reshape 

ar6 = np.random.rand(3,4)
ar6

array([[0.72000113, 0.57419759, 0.35277456, 0.40070153],
       [0.09627439, 0.53413734, 0.84480616, 0.50437081],
       [0.41628691, 0.25607996, 0.89053216, 0.09435562]])

In [13]:
a= ar6.reshape(6,2) # reshape 3,4 to 6X2
a

array([[0.72000113, 0.57419759],
       [0.35277456, 0.40070153],
       [0.09627439, 0.53413734],
       [0.84480616, 0.50437081],
       [0.41628691, 0.25607996],
       [0.89053216, 0.09435562]])

In [16]:
a=ar6.reshape(6,-124584)
a

array([[0.72000113, 0.57419759],
       [0.35277456, 0.40070153],
       [0.09627439, 0.53413734],
       [0.84480616, 0.50437081],
       [0.41628691, 0.25607996],
       [0.89053216, 0.09435562]])

In [20]:
a[2][1]

np.float64(0.5341373441390594)

In [23]:
a[2:5][2]

array([0.41628691, 0.25607996])

In [24]:
a[2:5,1]

array([0.53413734, 0.50437081, 0.25607996])

In [25]:
a1 = np.array([1, 2, 3, 4, 5, 6])

index = np.where(a1==3)
index

(array([2]),)

In [26]:
ar7 = np.random.randint(1,110, (5,5))
ar7

array([[ 13,  70,  43,  84,  36],
       [ 30,  92,  85,   9,  60],
       [106, 107,  13,   7,  79],
       [ 49,   2,   5,  17,  75],
       [ 74,  27,  50, 100,   4]], dtype=int32)

In [27]:
ar7 >50

array([[False,  True, False,  True, False],
       [False,  True,  True, False,  True],
       [ True,  True, False, False,  True],
       [False, False, False, False,  True],
       [ True, False, False,  True, False]])

In [37]:
ar7[ar7 >50]

array([ 70,  84,  92,  85,  60, 106, 107,  79,  75,  74, 100], dtype=int32)

In [38]:
ar7

array([[ 13,  70,  43,  84,  36],
       [ 30,  92,  85,   9,  60],
       [106, 107,  13,   7,  79],
       [ 49,   2,   5,  17,  75],
       [ 74,  27,  50, 100,   4]], dtype=int32)

In [39]:
ar7[2:4 , [1,2]]  #2:4 rows , 1,2 col

array([[107,  13],
       [  2,   5]], dtype=int32)

In [40]:
ar7[0,0]  #[0][0]

np.int32(13)

In [41]:
ar7[0,0]=500
ar7

array([[500,  70,  43,  84,  36],
       [ 30,  92,  85,   9,  60],
       [106, 107,  13,   7,  79],
       [ 49,   2,   5,  17,  75],
       [ 74,  27,  50, 100,   4]], dtype=int32)

In [43]:
arr1= np.random.randint(1,3 , (3,3))
arr2= np.random.randint(1,3 , (3,3))

In [44]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [1, 1, 1]], dtype=int32)

In [45]:
arr2

array([[2, 2, 1],
       [1, 1, 2],
       [2, 2, 1]], dtype=int32)

In [46]:
arr1+arr2 #this not matrix sum , this is index sum

array([[3, 3, 3],
       [3, 2, 4],
       [3, 3, 2]], dtype=int32)

In [ ]:
#-martix multiplication , 1 rule 1m rxC , 2m Rxc  C of 1m and R of 2m should be equal

2,2,1   1,2,2      2x1+2x2+1x1  2x2+2x1+1x1  2x2+2x1+1x1 = 7 7 7 
2,1,2   2,1,1      2x1+1x2+2x1  2x2+1x1+2x1  
1,2,1   1,1,1

In [47]:
arr1@arr2   #----@ help to multiply matrix

array([[7, 7, 5],
       [9, 9, 6],
       [5, 5, 4]], dtype=int32)

In [48]:
arr1/0 #infinity

C:\Users\nusra\AppData\Local\Temp\ipykernel_5960\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [51]:
arr1+100

array([[101, 101, 102],
       [102, 101, 102],
       [101, 101, 101]], dtype=int32)

In [52]:
arr2**2

array([[4, 4, 1],
       [1, 1, 4],
       [4, 4, 1]], dtype=int32)

In [50]:
#---------broadcasting  , row by row broadcasting kr ra h , means change entier row
 
arr3 = np.zeros((4,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [57]:
arr3+row # row row by addition 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [58]:
#----------col wise broadcasting , firslty rotate row , but rotation only 2d

row2 = np.array([[1,2,3,4]])
row2

array([[1, 2, 3, 4]])

In [59]:
row2.T # transpose rotate into row to col

array([[1],
       [2],
       [3],
       [4]])

In [64]:
add_arr=row2.T+arr3    # then broadcasting
add_arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [66]:
add_arr[1]=100
add_arr

array([[  1.,   1.,   1.,   1.],
       [100., 100., 100., 100.],
       [  3.,   3.,   3.,   3.],
       [  4.,   4.,   4.,   4.]])

In [67]:
arr4 = np.random.randint(5,7 ,(3,4))
arr4

array([[6, 5, 6, 5],
       [5, 5, 6, 5],
       [6, 6, 6, 5]], dtype=int32)

In [68]:
np.sqrt(arr4)

array([[2.44948974, 2.23606798, 2.44948974, 2.23606798],
       [2.23606798, 2.23606798, 2.44948974, 2.23606798],
       [2.44948974, 2.44948974, 2.44948974, 2.23606798]])

In [69]:
np.log10(arr4)

array([[0.77815125, 0.69897   , 0.77815125, 0.69897   ],
       [0.69897   , 0.69897   , 0.77815125, 0.69897   ],
       [0.77815125, 0.77815125, 0.77815125, 0.69897   ]])

In [70]:
np.min(arr4)

np.int32(5)